pipeline:
  name: hello_world
  identifier: hello_world
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: hello-step
                  identifier: hellostep
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello from Harness Pipeline"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: demo
            deployToAll: false
        tags: {}
    - stage:
        name: artifact
        identifier: artifact
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: artifact_test
                  identifier: artifact_test
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Cleaning old artifact"
                          rm -rf output

                          echo "Creating artifact directory"
                          mkdir output

                          echo "Hello from artifact stage" > output/app.txt

                          echo "Showing artifact contents"
                          ls -R output
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: Approval
        identifier: Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Approve Release
                  identifier: approve_release
                  spec:
                    approvalMessage: Please review the build and approve deployment.
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
        tags: {}
        when:
          pipelineStatus: Success
          condition: <+pipeline.stages.artifact.status> == "SUCCEEDED"
  variables:
    - name: input1
      type: String
      description: ""
      required: false
      value: value1
